# 4.0 Modelos de aprendizaje automático (Machine Learning)

## 4.1. Regresión lineal

### Scikit-learn

  - Posee herramientas eficientes para el aprendizaje automático y el modelado estadístico incluida:
    
    1. Clasificación
    2. Regresión
    3. Agrupamiento
    4. Reducción de la dimendcinalidad

#### Regresión lineal

La regreción lineal es un algoritmo de aprendizaje automático basado en el aprendizaje supervisado.

La regresión lineal intenta modelar la relación entre dos (o más) variables ajustando una linea recta a los datos, intenta predecir el valor de uan variable, en función del valor de otra (u otras variables).

### Desafío

Encontrar la relación entre las variables "experiencia" y "salario" del dataframe.

  1. Dividir el dataframe en dos matrices:

    - La matriz 1 contendrá las caracteristicas dependientes (salario).
    - La matriz independiente o destino (experiencia)

  2. Usar el 80% de los datos para entrenar el modelo y el otro 20% para probarlo. Hace uso de la función `train_test_split()` de scikit-learn.

### Code | Regresión lineal

In [44]:
### Code | Regresión lineal

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [45]:
df = pd.read_csv('../data/empleados_ml_lr.csv', delimiter=";")
df.head()

,Nombre,Sexo,Estado_Civil,Edad,Experiencia,Salario,Gerencia,Departamento
0,Alexandro,Masculino,Soltero(a),22,3,2423,No,Publicidad
1,Felipa,Femenino,Soltero(a),26,5,2639,No,Comercial
2,Daniel,Masculino,Casado(a),35,10,3122,No,Comercial
3,John,Masculino,Casado(a),35,13,3431,Sí,Servicios al cliente
4,Ruperta,Femenino,Casado(a),54,18,3962,No,Producto

In [46]:
X = df['Experiencia'].values.reshape(-1, 1)
y = df['Salario'].values.reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

linear_regressor = LinearRegression()
linear_regressor.fit(X_train, y_train)

print('Coeficiente de regresión:', linear_regressor.coef_[0][0])
print('Puntaje de regresión:', linear_regressor.score(X_test, y_test))

Coeficiente de regresión: 107.8097641808295
Puntaje de regresión: 0.9900562095952324

#### Analisis

**Coeficiente de regresión**: Nos indica que por cada año de experiencia, los empleados ganan aproximadamente $100 mas por cada año de experiencia. 

**Puntaje de regresión**: Nos indica un alto nivel de correlación entre las variables, lo cual las vuelve viables para el modelo.

## 4.2. Regresión lianeal multiple

### Regresión lineal múltiple (MLR)

Es uan técnica estadística que utiliza varias varibles explicativas para predecir el resultado de una variable de respuestas.

La regresión lineal multiple modela la relación lineal entre las variables explicativas (independientes) y las varibles de respuesta (dependiente).

### Desafío

Predecir el dióxido de carbono que emite un automóvil a partir de su longitud, anchura y altura.

  1. Dividir los datos en conjuntos de entrenamiento y pruebam usamos un 20% de nuestros datos para validación.
  2. Crear un modelo de regresión lineal multiple.
  3. Hacer predicciones basadas en el modelo con datos de prueba.
  4. Obteer el error medio, el error cuadrático medio y la raíx del error cuadrático medio.

### Code | Regresión lianeal multiple

In [47]:
### Code | Regresión lianeal multiple


import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
import numpy as np

In [48]:
df = pd.read_csv('../data/emisiones_MLR.csv', delimiter=";")
df.head()

        Marca  Longitud  Anchura  Altura  Maletero  CO2
0        Aero     4.495    1.840   1.540       320  294
1  Ality Auto     4.377    1.806   1.590       439  237
2       Amber     4.355    1.805   1.535       401  228
3    Ape Auto     3.698    1.720   1.484       170  207
4        Apex     4.535    1.770   1.480       624  327

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Marca     91 non-null     object
 1   Longitud  91 non-null     float64
 2   Anchura   91 non-null     float64
 3   Altura    91 non-null     float64
 4   Maletero  91 non-null     int64
 5   CO2       91 non-null     int64
dtypes: float64(3), int64(2), object(1)
memory usage: 4.4+ KB

In [52]:
X = df[['Longitud', 'Anchura', 'Altura']]
y = df['CO2']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

linear_regressor = LinearRegression()
linear_regressor.fit(X_train, y_train)
y_pred = linear_regressor.predict(X_test)

In [55]:
print(f"Error Medio Absoluto (MAE): {metrics.mean_absolute_error(y_test, y_pred)}")
print(f"Error Cuadrático Medio (MSE): {metrics.mean_squared_error(y_test, y_pred)}")
print(f"Raíz del Error Cuadrático Medio (RMSE): {np.sqrt(metrics.mean_squared_error(y_test, y_pred))}")

Error Medio Absoluto (MAE): 33.95613389641443
Error Cuadrático Medio (MSE): 1744.78489420768
Raíz del Error Cuadrático Medio (RMSE): 41.77062238233565

  - **Error Medio Absoluto (MAE)**: Es la diferencia, tomada siempre en positivo, entre el valor real y el valor aproximado.
  - **Error Cuadrático Medio (MSE)**: 
  - **Raíz del Error Cuadrático Medio (RMSE)**: El RMSE nos indica cuanto podria equivocarsenuestro modelo alsumar o restar el RMSE al valor real,entre mas cercano estea $0$, la presición es mejor.

## 4.3. Regresión logistica

### Regresión logistica

La regresión logistica tienecomo objetivo resolver problemas de clasificación,mediante la predicción de resultados categóricos.

Existen dos tipos de predicciones logisticas:

  - Binomial: Hay dos resultados (pe. Predecir si un tumor el maligno o benigno).
  - Multinomial: Mas de dos resultados (pe. predecir la clase de flor de iris entre especies diferentes).

### Desafío

Usar la regresión logística básica para predecir si un estudiante pasa o no un examen en función de las horas que ha estudiado.

### Code | Regresión logistica

In [ ]:
### Code | Regresión logística

## 4.4. Arboles de desición (Decision Tree Classifier)

### Code | Arboles de desición (Decision Tree Classifier)

In [ ]:
### Code | Arboles de desición (Decision Tree Classifier)

## 4.5. Bosque aleatorio Clasificación (Random forest)

### Code | Bosque aleatorio Clasificación (Random forest)

In [ ]:
### Code | Bosque aleatorio Clasificación (Random forest)

## 4.6. Detección de valores atípicos (Local Outlier Factor)

### Code | Detección de valores atípicos (Local Outlier Factor)

In [ ]:
### Code | Detección de valores atípicos (Local Outlier Factor)

## 4.7. Bosque de aislamiento (Isolation forest)

### Code | Bosque de aislamiento (Isolation forest)

In [ ]:
### Code | Bosque de aislamiento (Isolation forest)

## 4.8. Aumento de gradiente (Gradient Boosting)

### Code | Aumento de gradiente (Gradient Boosting)

In [ ]:
### Code | Aumento de gradiente (Gradient Boosting)

## 4.9. Bayesiano ingenuo multinomial (MultinomialNB)

### Code | Bayesiano ingenuo multinomial (MultinomialNB)

In [ ]:
### Code | Bayesiano ingenuo multinomial (MultinomialNB)